### ISSUE TITLE
Impossible to compile OBJCXX Test

### ISSUE THREAD

**Issue by Heruabollo** [macmade/OBJCXX#15]
Windows version: Windows 10 Education
Visual studio version: Visual studio Enterprise 2015
Build in 32-bits

When I'm trying to build the Test solution under Visual studio Enterprise 2015, I have these errors:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'reinterpret_cast': cannot convert from 'overloaded-function' to 'IMP'	Test	C:\Users\\...\OBJCXX-master\OBJCXX-master\OBJCXX\include\OBJCXX\ClassBuilder.hpp	138	

> Severity Code	Description	Project	File	Line	Suppression State
Error	C2198	'bool (__cdecl *)(Class,SEL,IMP,const char *)': too few arguments for call	Test	C:\Users\\...\OBJCXX-master\OBJCXX-master\OBJCXX\include\OBJCXX\ClassBuilder.hpp	140	

Any Idea ?

Thanks :),

Heru.

**Comment by macmade** [comment]
Thanks for the report. This issue has been fixed in 6cd9b53be63aa8040a291b03a2008a6217778eac.
